import "../Content/ts/helper/Helper.Article";
import "../Content/ts/helper/Helper.Contact.Extension";
import "../Content/ts/helper/Helper.ProductFamiliy";
import "../Content/ts/helper/Helper.QuantityUnit";
import "../Content/ts/ArticleDetailsViewModel";
import "../Content/ts/ArticleCompanyRelationshipListViewModel";
import "../Content/ts/ArticleRelationshipListViewModel";
import "../Content/ts/ArticleDetailsRelationshipsTabViewModel";
import "../Content/ts/ArticleDetailsDocumentsTabViewModel";
import "../Content/ts/ArticleDetailsPricesTabViewModel";
import "../Content/ts/ArticleDetailsSerialsTabViewModel";
import "../Content/ts/ArticleRelationshipEditModalViewModel";
import "../Content/ts/ProductFamilyCreateViewModel";
import "../Content/ts/ProductFamilyDetailsViewModel";
import "../Content/ts/OfflineModel";
import "../Content/ts/ArticleCompanyRelationshipEditModalViewModel";
import "../Content/ts/jaydata.custom.functions";
import "../Content/ts/validation-rules";
import "../Content/ts/ArticleListIndexViewModel";
import "../Content/ts/ArticleCreateViewModel";
import "../Content/ts/ProductFamilyListIndexViewModel";
import "../Content/ts/CompanyDetailsRelationshipsTabViewModelExtension";
import "../Content/ts/LocationEditModalViewModel";
import "../Content/ts/StorageAreaEditModalViewModel";
import "../Content/ts/StoreEditModalViewModel";
import "../Content/ts/StoreDetailsLocationsTabViewModel";
import "../Content/ts/StoreDetailsStorageAreasTabViewModel";
import "../Content/ts/StoreDetailsViewModel";
import "../Content/ts/StoreListIndexViewModel";
import "../Content/ts/ArticleDetailsStockTabViewModel";
import {HelperStore} from "../Content/ts/helper/Helper.Store";
import "../Content/ts/QuantityUnitEntryListIndexViewModel";
import "../Content/ts/QuantityUnitEntryDetailsViewModel";
import "../Content/ts/QuantityUnitEntryEditModalViewModel";
import "../Content/ts/CompanyDetailsViewModelExtension";
import "../Content/ts/CompanyDetailsPricesTabViewModel";
import "../Content/ts/PriceSelectorViewModel";
import "../Content/ts/ArticleDetailsQuantityUnitsTabViewModel";
import "../Content/ts/ArticleDetailsUsersTabViewModel";
import "../Content/ts/ArticleUserRelationshipEditModalViewModel";
import "../Content/ts/UserDetailsArticlesTabViewModel";
import "../Content/ts/OverlappingArticleUserRelationshipValidator";
import "../Content/ts/ArticleDetailsDowntimesTabViewModel";
import "../Content/ts/ArticleDowntimeEditModalViewModel";
import {HelperQuantityUnit} from "@Crm.Article/helper/Helper.QuantityUnit";
import {HelperArticle} from "@Crm.Article/helper/Helper.Article";
import {HelperProductFamily} from "@Crm.Article/helper/Helper.ProductFamiliy";
import {HelperSerial} from "@Crm.Article/helper/Helper.Serial";

window.Helper.Article ||= HelperArticle;
window.Helper.ProductFamily ||= HelperProductFamily;
window.Helper.QuantityUnit ||= HelperQuantityUnit;
window.Helper.Store ||= HelperStore;
window.Helper.Serial ||= HelperSerial;